### ISSUE TITLE
Keyboard shortcut between TI elements

### ISSUE THREAD

**Issue by ivanstegic** [rdbrck/jira-template-injector#18]
## Summary

Quick jump to next selected `TI` element using a shortcut key, not a click.
## Details

The functionality of the injector that lets you click on the default text between `TI` elements, then automatically selecting it, is excellent. After you're done typing, you then simply click on the next set of text and continue. It would be **even better** if you could just `TAB` to the next set of `TI` elements, like tabbing between fields works. The actual `TAB` key won't work, but something like the back tick would.
## Additional Information
- Create new JIRA issue.
- Select a different issue type, or use the selected one.
- Press `TAB` to get to the **Description** field. Or, click on the **Description** field.
- Press the back tick key ```
- First set of `TI` elements is selected.
- Start typing your words.
- Press the back tick key ```
- Next set of `TI` elements is selected.
- Rinse, repeat.

I'm happy to contribute code as I am able to if this gets accepted as a valid enhancement.

**Comment by cfoucher** [comment]
This is a great idea. We will work on implementing this. Thanks for the feedback!

**Comment by cfoucher** [comment]
This has been implemented. Closing the issue.
Thanks for the great idea!
