### ISSUE TITLE
Template for Projects

### ISSUE THREAD

**Issue by hechi** [rdbrck/jira-template-injector#30]
Hey guys,

thanks for your awesome work. I like it really much and it speed up productivity in my team :)
Unfortunately, we have several projects and in some the requirements for the template are somewhat different. It would be great if you could assign the template to projects.

It would be a cool feature and would make the plugin even much cooler than it is without already :)
Greez

**Comment by cfoucher** [comment]
Great idea @hechi! We'll work on getting this in the next release.

**Comment by cfoucher** [comment]
A new version of JTI has been released to the Chrome Web Store with this functionality. Give it a shot and let us know how it works for you.
Thanks!
