### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by cboseak** [rdbrck/jira-template-injector#32]
could not get this to work. Uninstall prompt mentioned creating a ticket if it was due to functionality. Please let me know what information you need to diagnose issue.

**Comment by cboseak** [comment]
also figured I would mention that I followed the directions as far as closing jira windows. I tried closing and re-opening chrome. Also rebooted

**Comment by cfoucher** [comment]
Hi @cboseak,

Thanks for reaching out! Sorry to hear the extension isn't working for you.
A couple of things to check, 
- The extension only supports atlassian cloud instances (*.atlassian.net domains) as we need to set this in the manifest. If you're using an on premise solution and have a custom domain you will need to modify the manifest file with your custom domain.
- When you open the pop-up window (clicking on the extension icon), does it list the default templates, and does the 'BUG TEMPLATE' contain any text in the edit view? ([https://screencast.com/t/rRPqdWoC](https://screencast.com/t/rRPqdWoC))
- Are you trying to use custom Issue Types? By default the JTI only loads templates for a few standard Issue Types. If you have a 'Story', 'Bug' or 'Epic' Issue Type, can you see if the templates get injected for those? https://screencast.com/t/flUfAp9NjI (If you are using custom Issue Types, the text in the Issue Type fields needs to be an exact match - including case)

If all of that checks out, can you check the developer console for both the extension background page ([https://screencast.com/t/q4AW48Hxk](https://screencast.com/t/q4AW48Hxk)) and the Jira page you are trying to use the extension with for errors.

Thanks!

**Comment by cboseak** [comment]
Thanks for reaching out. That might be the issue... ours is self hosted on
prem. I ended up just writing a custom one for my own use. nothing fancy,
just grabs the dom element for description and auto inserts my template.
Feel free to close the ticket since its not a issue with your software but
rather our jira implementation

**Comment by cfoucher** [comment]
@cboseak 

Just FYI, if you still wanted to use this extension, it's a simple matter of modifying the manifest file from:
`"content_scripts": [
        {
            "matches": [
                "http://*.atlassian.net/*",
                "https://*.atlassian.net/*"
            ],`
to:
`"content_scripts": [
        {
            "matches": [
                "http://*.<you're-domain-here>.<tld>/*",
                "https://*.<you're-domain-here>.<tld>/*"
            ],`
