### ISSUE TITLE
Can not load Template

### ISSUE THREAD

**Issue by hechi** [rdbrck/jira-template-injector#34]
Hey guys, 
very very thanks that you develop the awesome project field from #30 Really nice to see how fast you are :)

I was so exited to test it today, but i cant load the template from an URL or a file :(
Loading the default works.

1.)
* Update App from ChromeWebStore (Version 1.2.2)
* Change my template to the new layout with project field etc.
* load from URL like in the previous version
** Then i got "Invalid URL...)
![screenshot_20170526_101049](https://cloud.githubusercontent.com/assets/3808354/26486536/cbe8d8e2-41fb-11e7-95e9-d3aec657433e.png)

2.) 
* download the default template from github you kindly provide
* click on file and select file i downloaded
* window disappear, app popup disappear 
* nothing happened, if i click again on the JTI file is not selected anymore and so i can not click on "Upload File"

I closed chrome, deleted cache, enabled/disabled the app.

If i can provide more information let me know :)

Servus

**Comment by cfoucher** [comment]
Hello @hechi 

Sorry to hear it's not working for you. 
Could you provide the url you are trying to test with?
For an example of a working url, you can try using the default Template json file hosted on Github -> [https://raw.githubusercontent.com/rdbrck/jira-template-injector/master/src/data/templates.json](https://raw.githubusercontent.com/rdbrck/jira-template-injector/master/src/data/templates.json)

In regards to the file upload functionality, are you running Chrome on Linux? It is a known bug that the file selector window doesn't work with extension popup windows on Linux.
Unfortunately until Chrome fixes this issue, there isn't much we can do.

**Comment by hechi** [comment]
Hey @cfoucher,

sry for the late response. I tried your url and it works, so i looked again at my json template and there was a semicolon to much, which makes my template invalid :( Now i can load the template but no success.
![image](https://cloud.githubusercontent.com/assets/3808354/26817791/45d1417c-4a98-11e7-8284-97ab712938cc.png). Here is my template that i used https://gist.github.com/hechi/166b115c9ab20dde3f412203268de1eb



Yes, i am running Chrome on Linux. So i had to wait and this is ok for me.

**Comment by cfoucher** [comment]
Hi @hechi 

I've looked over your setup, and it looks correct except for the Issue Type Field, you have "BUG" when I believe it needs to be "Bug". The parsing is case sensitive.
Have you tried the "Task" type? That one looks correct.

**Comment by hechi** [comment]
Ah ok perfect, now it works :) thanks a lot for your help :+1:
