### ISSUE TITLE
Not working for self-hosted JIRA instances

### ISSUE THREAD

**Issue by xavernitsch** [rdbrck/jira-template-injector#35]
Hello,
can't the domains where your extension works be configurable by the user?

manifest.json:35
`
"matches": [
  "http://*.atlassian.net/*",
  "https://*.atlassian.net/*"
`

**Comment by cfoucher** [comment]
Hello @xavernitsch,

We do realise this is a limitation of the app. We are currently working on an update that will allow users to specify which domains the extension should run on.

Thanks!

**Comment by DrillSergeant** [comment]
That option would be nice I would be able to use this extension. Watching this issue now and hope you guys find time to implement and release it soonish.

**Comment by michaelhofer** [comment]
I'd love to see this as well.

**Comment by cfoucher** [comment]
Version 1.2.3 is rolling out now with the ability to specify custom domains for the extension to run on. Please give it a shot let us know how it works. Thanks!

**Comment by xavernitsch** [comment]
Hey, great! Thank you very much! It's great!

**Comment by DrillSergeant** [comment]
Good job, thank you guys. It works!
