### ISSUE TITLE
Error parsing JSON template

### ISSUE THREAD

**Issue by ajgisme** [rdbrck/jira-template-injector#40]
I tried downloading loading a JSON template from a URL and when clicking the download button nothing happens.

I then tried to upload the file directly but I receive the following error:
"Error parsing JSON. Please verify contents."

The file is valid JSON and it worked a few months ago when I last uploaded it.
It seems that it's stopped working for me.

Please see the json file attached. (I renamed it to .txt so that it could be uploaded here; normally it's .json.)
[default.txt](https://github.com/rdbrck/jira-template-injector/files/1421541/default.txt)

**Comment by cfoucher** [comment]
Hi @ajgisme,

With the recent update to support self-hosted JIRA instances, the JSON format has slightly changed. The `options` object now requires both `limit` and `domains`. 
I don't see a reason they need to be enforced if they are empty, so we will remove that restriction in a future update. For the meantime, if you add the `domains` key to the JSON file it should load fine.
[default.txt](https://github.com/rdbrck/jira-template-injector/files/1422784/default.txt)


We will also look into why the load JSON from URL option is not working as intended. 

Thanks!

**Comment by cfoucher** [comment]
We have removed the requirement for each field to be present in the JSON file. 
Your original file should work now.
Thanks for the issue report!
