### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by ekussberg** [rdbrck/jira-template-injector#52]
Hey,

first to say it is a great plugin. I have just tried to export all templates and it doesn't work. Where is this JSON then saved?

**Comment by Noel91** [comment]
Hello ekussberg,

if you click export, you get an .json file in your browser as "download".
Maybe you have an blocker....

**Comment by ekussberg** [comment]
@Noel91 i have tried it out and found a fix for that:

`$(document).on('click', 'a#export', function () {
        if (browserType !== 'Edge') {
            chrome.runtime.sendMessage({
                JDTIfunction: 'getData'
            }, function (response) {
                if (response.status === 'success') {
                    var data = JSON.stringify(response.data, undefined, 4);
                    var blob = new Blob([data], {type: 'text/json;charset=utf-8'});
                    var filename = 'templates.json';
                    // Generate file for download
                    if(window.navigator.msSaveOrOpenBlob) {
                        window.navigator.msSaveBlob(blob, filename);
                    }
                    else{
                        var a = window.document.createElement('a');
                        a.href = window.URL.createObjectURL(blob);
                        a.download = 'jira-templates.json';
                        a.target = '_blank';
                        // Append anchor to body.
                        document.body.appendChild(a);
                        a.click();
                        // Remove anchor from body
                        document.body.removeChild(a);
                    }
                } else {
                    if (response.message) {
                        Materialize.toast(response.message, 2000, 'toastNotification');
                    } else {
                        Materialize.toast('Something went wrong. Please try again.', 2000, 'toastNotification');
                    }
                }
            });
        } else {
            chrome.tabs.create({'url': chrome.extension.getURL('/html/download.html')}, function (tab) {
                // Tab opened.
            });
        }
    });`

**Comment by cfoucher** [comment]
I am encountering the same issue.

**Comment by sdevalapurkar** [comment]
Yeah it seems like this issue is persisting on MacOS and not on windows or linux

**Comment by sdevalapurkar** [comment]
Thanks for your suggested fix, @ekussberg 👍

**Comment by sdevalapurkar** [comment]
The FileSaver library code being used by JTI just wasn't up to date. Should be good now :)
