### ISSUE TITLE
This extension violates the Chrome Web Store policy.

### ISSUE THREAD

**Issue by peterneave** [rdbrck/jira-template-injector#69]
Extension has been blocked by Chrome Web Store.

**Comment by laingawbl** [comment]
We think we've identified the reason - it has to do with the set of host permissions we were requesting on the extension. We're going to try submitting it again. Thanks for reporting the issue!

**Comment by laingawbl** [comment]
It's back! https://chrome.google.com/webstore/detail/jira-template-injector/hmhpegjieopgbdmpocdmfkafjgcdmhha
